// Code generated by entc, DO NOT EDIT.

package charmmodel

const (
	// Label holds the string label denoting the charmmodel type in the database.
	Label = "charm_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the charmmodel in the database.
	Table = "charm_models"
)

// Columns holds all SQL columns for charmmodel fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
