// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GardensColumns holds the columns for the "gardens" table.
	GardensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "location", Type: field.TypeString},
		{Name: "mentorship_id", Type: field.TypeUint64},
	}
	// GardensTable holds the schema information for the "gardens" table.
	GardensTable = &schema.Table{
		Name:       "gardens",
		Columns:    GardensColumns,
		PrimaryKey: []*schema.Column{GardensColumns[0]},
	}
	// MentorshipsColumns holds the columns for the "mentorships" table.
	MentorshipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// MentorshipsTable holds the schema information for the "mentorships" table.
	MentorshipsTable = &schema.Table{
		Name:       "mentorships",
		Columns:    MentorshipsColumns,
		PrimaryKey: []*schema.Column{MentorshipsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GardensTable,
		MentorshipsTable,
	}
)

func init() {
}
