// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GardensColumns holds the columns for the "gardens" table.
	GardensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "location", Type: field.TypeString},
		{Name: "mentorship_system_id", Type: field.TypeUint64, Nullable: true},
	}
	// GardensTable holds the schema information for the "gardens" table.
	GardensTable = &schema.Table{
		Name:       "gardens",
		Columns:    GardensColumns,
		PrimaryKey: []*schema.Column{GardensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "garden_mentorship_system",
				Columns:    []*schema.Column{GardensColumns[3]},
				RefColumns: []*schema.Column{MentorshipSystemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// MentorshipSystemsColumns holds the columns for the "mentorship_systems" table.
	MentorshipSystemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// MentorshipSystemsTable holds the schema information for the "mentorship_systems" table.
	MentorshipSystemsTable = &schema.Table{
		Name:       "mentorship_systems",
		Columns:    MentorshipSystemsColumns,
		PrimaryKey: []*schema.Column{MentorshipSystemsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GardensTable,
		MentorshipSystemsTable,
	}
)

func init() {
	GardensTable.ForeignKeys[0].RefTable = MentorshipSystemsTable
}
