// Code generated by entc, DO NOT EDIT.

package charm

const (
	// Label holds the string label denoting the charm type in the database.
	Label = "charm"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the charm in the database.
	Table = "charms"
)

// Columns holds all SQL columns for charm fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
