// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"study-event-go/ent/charm"

	"entgo.io/ent/dialect/sql"
)

// Charm is the model entity for the Charm schema.
type Charm struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Charm) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case charm.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Charm", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Charm fields.
func (c *Charm) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case charm.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Charm.
// Note that you need to call Charm.Unwrap() before calling this method if this Charm
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Charm) Update() *CharmUpdateOne {
	return (&CharmClient{config: c.config}).UpdateOne(c)
}

// Unwrap unwraps the Charm entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Charm) Unwrap() *Charm {
	tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Charm is not a transactional entity")
	}
	c.config.driver = tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Charm) String() string {
	var builder strings.Builder
	builder.WriteString("Charm(")
	builder.WriteString(fmt.Sprintf("id=%v", c.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Charms is a parsable slice of Charm.
type Charms []*Charm

func (c Charms) config(cfg config) {
	for _i := range c {
		c[_i].config = cfg
	}
}
