// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"study-event-go/ent/charmmodel"
	"study-event-go/types"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CharmModelCreate is the builder for creating a CharmModel entity.
type CharmModelCreate struct {
	config
	mutation *CharmModelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (cmc *CharmModelCreate) SetCreatedAt(t time.Time) *CharmModelCreate {
	cmc.mutation.SetCreatedAt(t)
	return cmc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cmc *CharmModelCreate) SetNillableCreatedAt(t *time.Time) *CharmModelCreate {
	if t != nil {
		cmc.SetCreatedAt(*t)
	}
	return cmc
}

// SetUpdatedAt sets the "updated_at" field.
func (cmc *CharmModelCreate) SetUpdatedAt(t time.Time) *CharmModelCreate {
	cmc.mutation.SetUpdatedAt(t)
	return cmc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cmc *CharmModelCreate) SetNillableUpdatedAt(t *time.Time) *CharmModelCreate {
	if t != nil {
		cmc.SetUpdatedAt(*t)
	}
	return cmc
}

// SetDeletedAt sets the "deleted_at" field.
func (cmc *CharmModelCreate) SetDeletedAt(t time.Time) *CharmModelCreate {
	cmc.mutation.SetDeletedAt(t)
	return cmc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (cmc *CharmModelCreate) SetNillableDeletedAt(t *time.Time) *CharmModelCreate {
	if t != nil {
		cmc.SetDeletedAt(*t)
	}
	return cmc
}

// SetName sets the "name" field.
func (cmc *CharmModelCreate) SetName(s string) *CharmModelCreate {
	cmc.mutation.SetName(s)
	return cmc
}

// SetCreatorID sets the "creator_id" field.
func (cmc *CharmModelCreate) SetCreatorID(tci types.CharmCreatorID) *CharmModelCreate {
	cmc.mutation.SetCreatorID(tci)
	return cmc
}

// SetID sets the "id" field.
func (cmc *CharmModelCreate) SetID(tmi types.CharmModelID) *CharmModelCreate {
	cmc.mutation.SetID(tmi)
	return cmc
}

// Mutation returns the CharmModelMutation object of the builder.
func (cmc *CharmModelCreate) Mutation() *CharmModelMutation {
	return cmc.mutation
}

// Save creates the CharmModel in the database.
func (cmc *CharmModelCreate) Save(ctx context.Context) (*CharmModel, error) {
	var (
		err  error
		node *CharmModel
	)
	cmc.defaults()
	if len(cmc.hooks) == 0 {
		if err = cmc.check(); err != nil {
			return nil, err
		}
		node, err = cmc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CharmModelMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cmc.check(); err != nil {
				return nil, err
			}
			cmc.mutation = mutation
			if node, err = cmc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(cmc.hooks) - 1; i >= 0; i-- {
			if cmc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cmc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cmc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cmc *CharmModelCreate) SaveX(ctx context.Context) *CharmModel {
	v, err := cmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cmc *CharmModelCreate) Exec(ctx context.Context) error {
	_, err := cmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cmc *CharmModelCreate) ExecX(ctx context.Context) {
	if err := cmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cmc *CharmModelCreate) defaults() {
	if _, ok := cmc.mutation.CreatedAt(); !ok {
		v := charmmodel.DefaultCreatedAt()
		cmc.mutation.SetCreatedAt(v)
	}
	if _, ok := cmc.mutation.UpdatedAt(); !ok {
		v := charmmodel.DefaultUpdatedAt()
		cmc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cmc *CharmModelCreate) check() error {
	if _, ok := cmc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	if _, ok := cmc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "updated_at"`)}
	}
	if _, ok := cmc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "name"`)}
	}
	if v, ok := cmc.mutation.Name(); ok {
		if err := charmmodel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "name": %w`, err)}
		}
	}
	if _, ok := cmc.mutation.CreatorID(); !ok {
		return &ValidationError{Name: "creator_id", err: errors.New(`ent: missing required field "creator_id"`)}
	}
	return nil
}

func (cmc *CharmModelCreate) sqlSave(ctx context.Context) (*CharmModel, error) {
	_node, _spec := cmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = types.CharmModelID(id)
	}
	return _node, nil
}

func (cmc *CharmModelCreate) createSpec() (*CharmModel, *sqlgraph.CreateSpec) {
	var (
		_node = &CharmModel{config: cmc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: charmmodel.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: charmmodel.FieldID,
			},
		}
	)
	_spec.OnConflict = cmc.conflict
	if id, ok := cmc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cmc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: charmmodel.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := cmc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: charmmodel.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := cmc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: charmmodel.FieldDeletedAt,
		})
		_node.DeletedAt = &value
	}
	if value, ok := cmc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: charmmodel.FieldName,
		})
		_node.Name = value
	}
	if value, ok := cmc.mutation.CreatorID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: charmmodel.FieldCreatorID,
		})
		_node.CreatorID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CharmModel.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CharmModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (cmc *CharmModelCreate) OnConflict(opts ...sql.ConflictOption) *CharmModelUpsertOne {
	cmc.conflict = opts
	return &CharmModelUpsertOne{
		create: cmc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CharmModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (cmc *CharmModelCreate) OnConflictColumns(columns ...string) *CharmModelUpsertOne {
	cmc.conflict = append(cmc.conflict, sql.ConflictColumns(columns...))
	return &CharmModelUpsertOne{
		create: cmc,
	}
}

type (
	// CharmModelUpsertOne is the builder for "upsert"-ing
	//  one CharmModel node.
	CharmModelUpsertOne struct {
		create *CharmModelCreate
	}

	// CharmModelUpsert is the "OnConflict" setter.
	CharmModelUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *CharmModelUpsert) SetCreatedAt(v time.Time) *CharmModelUpsert {
	u.Set(charmmodel.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CharmModelUpsert) UpdateCreatedAt() *CharmModelUpsert {
	u.SetExcluded(charmmodel.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CharmModelUpsert) SetUpdatedAt(v time.Time) *CharmModelUpsert {
	u.Set(charmmodel.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CharmModelUpsert) UpdateUpdatedAt() *CharmModelUpsert {
	u.SetExcluded(charmmodel.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CharmModelUpsert) SetDeletedAt(v time.Time) *CharmModelUpsert {
	u.Set(charmmodel.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CharmModelUpsert) UpdateDeletedAt() *CharmModelUpsert {
	u.SetExcluded(charmmodel.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CharmModelUpsert) ClearDeletedAt() *CharmModelUpsert {
	u.SetNull(charmmodel.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *CharmModelUpsert) SetName(v string) *CharmModelUpsert {
	u.Set(charmmodel.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CharmModelUpsert) UpdateName() *CharmModelUpsert {
	u.SetExcluded(charmmodel.FieldName)
	return u
}

// SetCreatorID sets the "creator_id" field.
func (u *CharmModelUpsert) SetCreatorID(v types.CharmCreatorID) *CharmModelUpsert {
	u.Set(charmmodel.FieldCreatorID, v)
	return u
}

// UpdateCreatorID sets the "creator_id" field to the value that was provided on create.
func (u *CharmModelUpsert) UpdateCreatorID() *CharmModelUpsert {
	u.SetExcluded(charmmodel.FieldCreatorID)
	return u
}

// UpdateNewValues updates the fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CharmModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(charmmodel.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CharmModelUpsertOne) UpdateNewValues() *CharmModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(charmmodel.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.CharmModel.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *CharmModelUpsertOne) Ignore() *CharmModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CharmModelUpsertOne) DoNothing() *CharmModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CharmModelCreate.OnConflict
// documentation for more info.
func (u *CharmModelUpsertOne) Update(set func(*CharmModelUpsert)) *CharmModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CharmModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CharmModelUpsertOne) SetCreatedAt(v time.Time) *CharmModelUpsertOne {
	return u.Update(func(s *CharmModelUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CharmModelUpsertOne) UpdateCreatedAt() *CharmModelUpsertOne {
	return u.Update(func(s *CharmModelUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CharmModelUpsertOne) SetUpdatedAt(v time.Time) *CharmModelUpsertOne {
	return u.Update(func(s *CharmModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CharmModelUpsertOne) UpdateUpdatedAt() *CharmModelUpsertOne {
	return u.Update(func(s *CharmModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CharmModelUpsertOne) SetDeletedAt(v time.Time) *CharmModelUpsertOne {
	return u.Update(func(s *CharmModelUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CharmModelUpsertOne) UpdateDeletedAt() *CharmModelUpsertOne {
	return u.Update(func(s *CharmModelUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CharmModelUpsertOne) ClearDeletedAt() *CharmModelUpsertOne {
	return u.Update(func(s *CharmModelUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *CharmModelUpsertOne) SetName(v string) *CharmModelUpsertOne {
	return u.Update(func(s *CharmModelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CharmModelUpsertOne) UpdateName() *CharmModelUpsertOne {
	return u.Update(func(s *CharmModelUpsert) {
		s.UpdateName()
	})
}

// SetCreatorID sets the "creator_id" field.
func (u *CharmModelUpsertOne) SetCreatorID(v types.CharmCreatorID) *CharmModelUpsertOne {
	return u.Update(func(s *CharmModelUpsert) {
		s.SetCreatorID(v)
	})
}

// UpdateCreatorID sets the "creator_id" field to the value that was provided on create.
func (u *CharmModelUpsertOne) UpdateCreatorID() *CharmModelUpsertOne {
	return u.Update(func(s *CharmModelUpsert) {
		s.UpdateCreatorID()
	})
}

// Exec executes the query.
func (u *CharmModelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CharmModelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CharmModelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CharmModelUpsertOne) ID(ctx context.Context) (id types.CharmModelID, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CharmModelUpsertOne) IDX(ctx context.Context) types.CharmModelID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CharmModelCreateBulk is the builder for creating many CharmModel entities in bulk.
type CharmModelCreateBulk struct {
	config
	builders []*CharmModelCreate
	conflict []sql.ConflictOption
}

// Save creates the CharmModel entities in the database.
func (cmcb *CharmModelCreateBulk) Save(ctx context.Context) ([]*CharmModel, error) {
	specs := make([]*sqlgraph.CreateSpec, len(cmcb.builders))
	nodes := make([]*CharmModel, len(cmcb.builders))
	mutators := make([]Mutator, len(cmcb.builders))
	for i := range cmcb.builders {
		func(i int, root context.Context) {
			builder := cmcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CharmModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = cmcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = types.CharmModelID(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cmcb *CharmModelCreateBulk) SaveX(ctx context.Context) []*CharmModel {
	v, err := cmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cmcb *CharmModelCreateBulk) Exec(ctx context.Context) error {
	_, err := cmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cmcb *CharmModelCreateBulk) ExecX(ctx context.Context) {
	if err := cmcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CharmModel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CharmModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (cmcb *CharmModelCreateBulk) OnConflict(opts ...sql.ConflictOption) *CharmModelUpsertBulk {
	cmcb.conflict = opts
	return &CharmModelUpsertBulk{
		create: cmcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CharmModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (cmcb *CharmModelCreateBulk) OnConflictColumns(columns ...string) *CharmModelUpsertBulk {
	cmcb.conflict = append(cmcb.conflict, sql.ConflictColumns(columns...))
	return &CharmModelUpsertBulk{
		create: cmcb,
	}
}

// CharmModelUpsertBulk is the builder for "upsert"-ing
// a bulk of CharmModel nodes.
type CharmModelUpsertBulk struct {
	create *CharmModelCreateBulk
}

// UpdateNewValues updates the fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CharmModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(charmmodel.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CharmModelUpsertBulk) UpdateNewValues() *CharmModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(charmmodel.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CharmModel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *CharmModelUpsertBulk) Ignore() *CharmModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CharmModelUpsertBulk) DoNothing() *CharmModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CharmModelCreateBulk.OnConflict
// documentation for more info.
func (u *CharmModelUpsertBulk) Update(set func(*CharmModelUpsert)) *CharmModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CharmModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CharmModelUpsertBulk) SetCreatedAt(v time.Time) *CharmModelUpsertBulk {
	return u.Update(func(s *CharmModelUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CharmModelUpsertBulk) UpdateCreatedAt() *CharmModelUpsertBulk {
	return u.Update(func(s *CharmModelUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CharmModelUpsertBulk) SetUpdatedAt(v time.Time) *CharmModelUpsertBulk {
	return u.Update(func(s *CharmModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CharmModelUpsertBulk) UpdateUpdatedAt() *CharmModelUpsertBulk {
	return u.Update(func(s *CharmModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CharmModelUpsertBulk) SetDeletedAt(v time.Time) *CharmModelUpsertBulk {
	return u.Update(func(s *CharmModelUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CharmModelUpsertBulk) UpdateDeletedAt() *CharmModelUpsertBulk {
	return u.Update(func(s *CharmModelUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CharmModelUpsertBulk) ClearDeletedAt() *CharmModelUpsertBulk {
	return u.Update(func(s *CharmModelUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *CharmModelUpsertBulk) SetName(v string) *CharmModelUpsertBulk {
	return u.Update(func(s *CharmModelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CharmModelUpsertBulk) UpdateName() *CharmModelUpsertBulk {
	return u.Update(func(s *CharmModelUpsert) {
		s.UpdateName()
	})
}

// SetCreatorID sets the "creator_id" field.
func (u *CharmModelUpsertBulk) SetCreatorID(v types.CharmCreatorID) *CharmModelUpsertBulk {
	return u.Update(func(s *CharmModelUpsert) {
		s.SetCreatorID(v)
	})
}

// UpdateCreatorID sets the "creator_id" field to the value that was provided on create.
func (u *CharmModelUpsertBulk) UpdateCreatorID() *CharmModelUpsertBulk {
	return u.Update(func(s *CharmModelUpsert) {
		s.UpdateCreatorID()
	})
}

// Exec executes the query.
func (u *CharmModelUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CharmModelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CharmModelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CharmModelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
