// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"study_event_go/ent/migrate"
	"study_event_go/types"

	"study_event_go/ent/garden"
	"study_event_go/ent/mentorshipsystem"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Garden is the client for interacting with the Garden builders.
	Garden *GardenClient
	// MentorshipSystem is the client for interacting with the MentorshipSystem builders.
	MentorshipSystem *MentorshipSystemClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Garden = NewGardenClient(c.config)
	c.MentorshipSystem = NewMentorshipSystemClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		Garden:           NewGardenClient(cfg),
		MentorshipSystem: NewMentorshipSystemClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:           cfg,
		Garden:           NewGardenClient(cfg),
		MentorshipSystem: NewMentorshipSystemClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Garden.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Garden.Use(hooks...)
	c.MentorshipSystem.Use(hooks...)
}

// GardenClient is a client for the Garden schema.
type GardenClient struct {
	config
}

// NewGardenClient returns a client for the Garden from the given config.
func NewGardenClient(c config) *GardenClient {
	return &GardenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `garden.Hooks(f(g(h())))`.
func (c *GardenClient) Use(hooks ...Hook) {
	c.hooks.Garden = append(c.hooks.Garden, hooks...)
}

// Create returns a create builder for Garden.
func (c *GardenClient) Create() *GardenCreate {
	mutation := newGardenMutation(c.config, OpCreate)
	return &GardenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Garden entities.
func (c *GardenClient) CreateBulk(builders ...*GardenCreate) *GardenCreateBulk {
	return &GardenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Garden.
func (c *GardenClient) Update() *GardenUpdate {
	mutation := newGardenMutation(c.config, OpUpdate)
	return &GardenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GardenClient) UpdateOne(ga *Garden) *GardenUpdateOne {
	mutation := newGardenMutation(c.config, OpUpdateOne, withGarden(ga))
	return &GardenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GardenClient) UpdateOneID(id types.GardenID) *GardenUpdateOne {
	mutation := newGardenMutation(c.config, OpUpdateOne, withGardenID(id))
	return &GardenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Garden.
func (c *GardenClient) Delete() *GardenDelete {
	mutation := newGardenMutation(c.config, OpDelete)
	return &GardenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *GardenClient) DeleteOne(ga *Garden) *GardenDeleteOne {
	return c.DeleteOneID(ga.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *GardenClient) DeleteOneID(id types.GardenID) *GardenDeleteOne {
	builder := c.Delete().Where(garden.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GardenDeleteOne{builder}
}

// Query returns a query builder for Garden.
func (c *GardenClient) Query() *GardenQuery {
	return &GardenQuery{
		config: c.config,
	}
}

// Get returns a Garden entity by its id.
func (c *GardenClient) Get(ctx context.Context, id types.GardenID) (*Garden, error) {
	return c.Query().Where(garden.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GardenClient) GetX(ctx context.Context, id types.GardenID) *Garden {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMentorshipSystem queries the mentorship_system edge of a Garden.
func (c *GardenClient) QueryMentorshipSystem(ga *Garden) *MentorshipSystemQuery {
	query := &MentorshipSystemQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := ga.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(garden.Table, garden.FieldID, id),
			sqlgraph.To(mentorshipsystem.Table, mentorshipsystem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, garden.MentorshipSystemTable, garden.MentorshipSystemColumn),
		)
		fromV = sqlgraph.Neighbors(ga.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *GardenClient) Hooks() []Hook {
	return c.hooks.Garden
}

// MentorshipSystemClient is a client for the MentorshipSystem schema.
type MentorshipSystemClient struct {
	config
}

// NewMentorshipSystemClient returns a client for the MentorshipSystem from the given config.
func NewMentorshipSystemClient(c config) *MentorshipSystemClient {
	return &MentorshipSystemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `mentorshipsystem.Hooks(f(g(h())))`.
func (c *MentorshipSystemClient) Use(hooks ...Hook) {
	c.hooks.MentorshipSystem = append(c.hooks.MentorshipSystem, hooks...)
}

// Create returns a create builder for MentorshipSystem.
func (c *MentorshipSystemClient) Create() *MentorshipSystemCreate {
	mutation := newMentorshipSystemMutation(c.config, OpCreate)
	return &MentorshipSystemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MentorshipSystem entities.
func (c *MentorshipSystemClient) CreateBulk(builders ...*MentorshipSystemCreate) *MentorshipSystemCreateBulk {
	return &MentorshipSystemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MentorshipSystem.
func (c *MentorshipSystemClient) Update() *MentorshipSystemUpdate {
	mutation := newMentorshipSystemMutation(c.config, OpUpdate)
	return &MentorshipSystemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MentorshipSystemClient) UpdateOne(ms *MentorshipSystem) *MentorshipSystemUpdateOne {
	mutation := newMentorshipSystemMutation(c.config, OpUpdateOne, withMentorshipSystem(ms))
	return &MentorshipSystemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MentorshipSystemClient) UpdateOneID(id types.MentorshipSystemID) *MentorshipSystemUpdateOne {
	mutation := newMentorshipSystemMutation(c.config, OpUpdateOne, withMentorshipSystemID(id))
	return &MentorshipSystemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MentorshipSystem.
func (c *MentorshipSystemClient) Delete() *MentorshipSystemDelete {
	mutation := newMentorshipSystemMutation(c.config, OpDelete)
	return &MentorshipSystemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *MentorshipSystemClient) DeleteOne(ms *MentorshipSystem) *MentorshipSystemDeleteOne {
	return c.DeleteOneID(ms.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *MentorshipSystemClient) DeleteOneID(id types.MentorshipSystemID) *MentorshipSystemDeleteOne {
	builder := c.Delete().Where(mentorshipsystem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MentorshipSystemDeleteOne{builder}
}

// Query returns a query builder for MentorshipSystem.
func (c *MentorshipSystemClient) Query() *MentorshipSystemQuery {
	return &MentorshipSystemQuery{
		config: c.config,
	}
}

// Get returns a MentorshipSystem entity by its id.
func (c *MentorshipSystemClient) Get(ctx context.Context, id types.MentorshipSystemID) (*MentorshipSystem, error) {
	return c.Query().Where(mentorshipsystem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MentorshipSystemClient) GetX(ctx context.Context, id types.MentorshipSystemID) *MentorshipSystem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MentorshipSystemClient) Hooks() []Hook {
	return c.hooks.MentorshipSystem
}
