// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"study-event-go/ent/mentorshipsystem"
	"study-event-go/ent/predicate"
	"study-event-go/types"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MentorshipSystemQuery is the builder for querying MentorshipSystem entities.
type MentorshipSystemQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.MentorshipSystem
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MentorshipSystemQuery builder.
func (msq *MentorshipSystemQuery) Where(ps ...predicate.MentorshipSystem) *MentorshipSystemQuery {
	msq.predicates = append(msq.predicates, ps...)
	return msq
}

// Limit adds a limit step to the query.
func (msq *MentorshipSystemQuery) Limit(limit int) *MentorshipSystemQuery {
	msq.limit = &limit
	return msq
}

// Offset adds an offset step to the query.
func (msq *MentorshipSystemQuery) Offset(offset int) *MentorshipSystemQuery {
	msq.offset = &offset
	return msq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (msq *MentorshipSystemQuery) Unique(unique bool) *MentorshipSystemQuery {
	msq.unique = &unique
	return msq
}

// Order adds an order step to the query.
func (msq *MentorshipSystemQuery) Order(o ...OrderFunc) *MentorshipSystemQuery {
	msq.order = append(msq.order, o...)
	return msq
}

// First returns the first MentorshipSystem entity from the query.
// Returns a *NotFoundError when no MentorshipSystem was found.
func (msq *MentorshipSystemQuery) First(ctx context.Context) (*MentorshipSystem, error) {
	nodes, err := msq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mentorshipsystem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (msq *MentorshipSystemQuery) FirstX(ctx context.Context) *MentorshipSystem {
	node, err := msq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MentorshipSystem ID from the query.
// Returns a *NotFoundError when no MentorshipSystem ID was found.
func (msq *MentorshipSystemQuery) FirstID(ctx context.Context) (id types.MentorshipSystemID, err error) {
	var ids []types.MentorshipSystemID
	if ids, err = msq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mentorshipsystem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (msq *MentorshipSystemQuery) FirstIDX(ctx context.Context) types.MentorshipSystemID {
	id, err := msq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MentorshipSystem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one MentorshipSystem entity is not found.
// Returns a *NotFoundError when no MentorshipSystem entities are found.
func (msq *MentorshipSystemQuery) Only(ctx context.Context) (*MentorshipSystem, error) {
	nodes, err := msq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mentorshipsystem.Label}
	default:
		return nil, &NotSingularError{mentorshipsystem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (msq *MentorshipSystemQuery) OnlyX(ctx context.Context) *MentorshipSystem {
	node, err := msq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MentorshipSystem ID in the query.
// Returns a *NotSingularError when exactly one MentorshipSystem ID is not found.
// Returns a *NotFoundError when no entities are found.
func (msq *MentorshipSystemQuery) OnlyID(ctx context.Context) (id types.MentorshipSystemID, err error) {
	var ids []types.MentorshipSystemID
	if ids, err = msq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mentorshipsystem.Label}
	default:
		err = &NotSingularError{mentorshipsystem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (msq *MentorshipSystemQuery) OnlyIDX(ctx context.Context) types.MentorshipSystemID {
	id, err := msq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MentorshipSystems.
func (msq *MentorshipSystemQuery) All(ctx context.Context) ([]*MentorshipSystem, error) {
	if err := msq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return msq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (msq *MentorshipSystemQuery) AllX(ctx context.Context) []*MentorshipSystem {
	nodes, err := msq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MentorshipSystem IDs.
func (msq *MentorshipSystemQuery) IDs(ctx context.Context) ([]types.MentorshipSystemID, error) {
	var ids []types.MentorshipSystemID
	if err := msq.Select(mentorshipsystem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (msq *MentorshipSystemQuery) IDsX(ctx context.Context) []types.MentorshipSystemID {
	ids, err := msq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (msq *MentorshipSystemQuery) Count(ctx context.Context) (int, error) {
	if err := msq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return msq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (msq *MentorshipSystemQuery) CountX(ctx context.Context) int {
	count, err := msq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (msq *MentorshipSystemQuery) Exist(ctx context.Context) (bool, error) {
	if err := msq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return msq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (msq *MentorshipSystemQuery) ExistX(ctx context.Context) bool {
	exist, err := msq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MentorshipSystemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (msq *MentorshipSystemQuery) Clone() *MentorshipSystemQuery {
	if msq == nil {
		return nil
	}
	return &MentorshipSystemQuery{
		config:     msq.config,
		limit:      msq.limit,
		offset:     msq.offset,
		order:      append([]OrderFunc{}, msq.order...),
		predicates: append([]predicate.MentorshipSystem{}, msq.predicates...),
		// clone intermediate query.
		sql:  msq.sql.Clone(),
		path: msq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MentorshipSystem.Query().
//		GroupBy(mentorshipsystem.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (msq *MentorshipSystemQuery) GroupBy(field string, fields ...string) *MentorshipSystemGroupBy {
	group := &MentorshipSystemGroupBy{config: msq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := msq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return msq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.MentorshipSystem.Query().
//		Select(mentorshipsystem.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (msq *MentorshipSystemQuery) Select(fields ...string) *MentorshipSystemSelect {
	msq.fields = append(msq.fields, fields...)
	return &MentorshipSystemSelect{MentorshipSystemQuery: msq}
}

func (msq *MentorshipSystemQuery) prepareQuery(ctx context.Context) error {
	for _, f := range msq.fields {
		if !mentorshipsystem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if msq.path != nil {
		prev, err := msq.path(ctx)
		if err != nil {
			return err
		}
		msq.sql = prev
	}
	return nil
}

func (msq *MentorshipSystemQuery) sqlAll(ctx context.Context) ([]*MentorshipSystem, error) {
	var (
		nodes = []*MentorshipSystem{}
		_spec = msq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &MentorshipSystem{config: msq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, msq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (msq *MentorshipSystemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := msq.querySpec()
	return sqlgraph.CountNodes(ctx, msq.driver, _spec)
}

func (msq *MentorshipSystemQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := msq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (msq *MentorshipSystemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   mentorshipsystem.Table,
			Columns: mentorshipsystem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: mentorshipsystem.FieldID,
			},
		},
		From:   msq.sql,
		Unique: true,
	}
	if unique := msq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := msq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mentorshipsystem.FieldID)
		for i := range fields {
			if fields[i] != mentorshipsystem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := msq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := msq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := msq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := msq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (msq *MentorshipSystemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(msq.driver.Dialect())
	t1 := builder.Table(mentorshipsystem.Table)
	columns := msq.fields
	if len(columns) == 0 {
		columns = mentorshipsystem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if msq.sql != nil {
		selector = msq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range msq.predicates {
		p(selector)
	}
	for _, p := range msq.order {
		p(selector)
	}
	if offset := msq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := msq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MentorshipSystemGroupBy is the group-by builder for MentorshipSystem entities.
type MentorshipSystemGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (msgb *MentorshipSystemGroupBy) Aggregate(fns ...AggregateFunc) *MentorshipSystemGroupBy {
	msgb.fns = append(msgb.fns, fns...)
	return msgb
}

// Scan applies the group-by query and scans the result into the given value.
func (msgb *MentorshipSystemGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := msgb.path(ctx)
	if err != nil {
		return err
	}
	msgb.sql = query
	return msgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (msgb *MentorshipSystemGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := msgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (msgb *MentorshipSystemGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(msgb.fields) > 1 {
		return nil, errors.New("ent: MentorshipSystemGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := msgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (msgb *MentorshipSystemGroupBy) StringsX(ctx context.Context) []string {
	v, err := msgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (msgb *MentorshipSystemGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = msgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mentorshipsystem.Label}
	default:
		err = fmt.Errorf("ent: MentorshipSystemGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (msgb *MentorshipSystemGroupBy) StringX(ctx context.Context) string {
	v, err := msgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (msgb *MentorshipSystemGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(msgb.fields) > 1 {
		return nil, errors.New("ent: MentorshipSystemGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := msgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (msgb *MentorshipSystemGroupBy) IntsX(ctx context.Context) []int {
	v, err := msgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (msgb *MentorshipSystemGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = msgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mentorshipsystem.Label}
	default:
		err = fmt.Errorf("ent: MentorshipSystemGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (msgb *MentorshipSystemGroupBy) IntX(ctx context.Context) int {
	v, err := msgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (msgb *MentorshipSystemGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(msgb.fields) > 1 {
		return nil, errors.New("ent: MentorshipSystemGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := msgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (msgb *MentorshipSystemGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := msgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (msgb *MentorshipSystemGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = msgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mentorshipsystem.Label}
	default:
		err = fmt.Errorf("ent: MentorshipSystemGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (msgb *MentorshipSystemGroupBy) Float64X(ctx context.Context) float64 {
	v, err := msgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (msgb *MentorshipSystemGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(msgb.fields) > 1 {
		return nil, errors.New("ent: MentorshipSystemGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := msgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (msgb *MentorshipSystemGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := msgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (msgb *MentorshipSystemGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = msgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mentorshipsystem.Label}
	default:
		err = fmt.Errorf("ent: MentorshipSystemGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (msgb *MentorshipSystemGroupBy) BoolX(ctx context.Context) bool {
	v, err := msgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (msgb *MentorshipSystemGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range msgb.fields {
		if !mentorshipsystem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := msgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := msgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (msgb *MentorshipSystemGroupBy) sqlQuery() *sql.Selector {
	selector := msgb.sql.Select()
	aggregation := make([]string, 0, len(msgb.fns))
	for _, fn := range msgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(msgb.fields)+len(msgb.fns))
		for _, f := range msgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(msgb.fields...)...)
}

// MentorshipSystemSelect is the builder for selecting fields of MentorshipSystem entities.
type MentorshipSystemSelect struct {
	*MentorshipSystemQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (mss *MentorshipSystemSelect) Scan(ctx context.Context, v interface{}) error {
	if err := mss.prepareQuery(ctx); err != nil {
		return err
	}
	mss.sql = mss.MentorshipSystemQuery.sqlQuery(ctx)
	return mss.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mss *MentorshipSystemSelect) ScanX(ctx context.Context, v interface{}) {
	if err := mss.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (mss *MentorshipSystemSelect) Strings(ctx context.Context) ([]string, error) {
	if len(mss.fields) > 1 {
		return nil, errors.New("ent: MentorshipSystemSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := mss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mss *MentorshipSystemSelect) StringsX(ctx context.Context) []string {
	v, err := mss.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (mss *MentorshipSystemSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mss.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mentorshipsystem.Label}
	default:
		err = fmt.Errorf("ent: MentorshipSystemSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mss *MentorshipSystemSelect) StringX(ctx context.Context) string {
	v, err := mss.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (mss *MentorshipSystemSelect) Ints(ctx context.Context) ([]int, error) {
	if len(mss.fields) > 1 {
		return nil, errors.New("ent: MentorshipSystemSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := mss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mss *MentorshipSystemSelect) IntsX(ctx context.Context) []int {
	v, err := mss.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (mss *MentorshipSystemSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mss.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mentorshipsystem.Label}
	default:
		err = fmt.Errorf("ent: MentorshipSystemSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mss *MentorshipSystemSelect) IntX(ctx context.Context) int {
	v, err := mss.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (mss *MentorshipSystemSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(mss.fields) > 1 {
		return nil, errors.New("ent: MentorshipSystemSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := mss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mss *MentorshipSystemSelect) Float64sX(ctx context.Context) []float64 {
	v, err := mss.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (mss *MentorshipSystemSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mss.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mentorshipsystem.Label}
	default:
		err = fmt.Errorf("ent: MentorshipSystemSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mss *MentorshipSystemSelect) Float64X(ctx context.Context) float64 {
	v, err := mss.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (mss *MentorshipSystemSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(mss.fields) > 1 {
		return nil, errors.New("ent: MentorshipSystemSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := mss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mss *MentorshipSystemSelect) BoolsX(ctx context.Context) []bool {
	v, err := mss.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (mss *MentorshipSystemSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mss.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mentorshipsystem.Label}
	default:
		err = fmt.Errorf("ent: MentorshipSystemSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mss *MentorshipSystemSelect) BoolX(ctx context.Context) bool {
	v, err := mss.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mss *MentorshipSystemSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := mss.sql.Query()
	if err := mss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
