// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"study_event_go/ent/mentorshipsystem"
	"study_event_go/types"
	"time"

	"entgo.io/ent/dialect/sql"
)

// MentorshipSystem is the model entity for the MentorshipSystem schema.
type MentorshipSystem struct {
	config `json:"-"`
	// ID of the ent.
	ID types.MentorshipSystemID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MentorshipSystem) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case mentorshipsystem.FieldID:
			values[i] = new(sql.NullInt64)
		case mentorshipsystem.FieldName:
			values[i] = new(sql.NullString)
		case mentorshipsystem.FieldCreatedAt, mentorshipsystem.FieldUpdatedAt, mentorshipsystem.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type MentorshipSystem", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MentorshipSystem fields.
func (ms *MentorshipSystem) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mentorshipsystem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ms.ID = types.MentorshipSystemID(value.Int64)
		case mentorshipsystem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ms.CreatedAt = value.Time
			}
		case mentorshipsystem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ms.UpdatedAt = value.Time
			}
		case mentorshipsystem.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				ms.DeletedAt = new(time.Time)
				*ms.DeletedAt = value.Time
			}
		case mentorshipsystem.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ms.Name = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this MentorshipSystem.
// Note that you need to call MentorshipSystem.Unwrap() before calling this method if this MentorshipSystem
// was returned from a transaction, and the transaction was committed or rolled back.
func (ms *MentorshipSystem) Update() *MentorshipSystemUpdateOne {
	return (&MentorshipSystemClient{config: ms.config}).UpdateOne(ms)
}

// Unwrap unwraps the MentorshipSystem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ms *MentorshipSystem) Unwrap() *MentorshipSystem {
	tx, ok := ms.config.driver.(*txDriver)
	if !ok {
		panic("ent: MentorshipSystem is not a transactional entity")
	}
	ms.config.driver = tx.drv
	return ms
}

// String implements the fmt.Stringer.
func (ms *MentorshipSystem) String() string {
	var builder strings.Builder
	builder.WriteString("MentorshipSystem(")
	builder.WriteString(fmt.Sprintf("id=%v", ms.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(ms.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(ms.UpdatedAt.Format(time.ANSIC))
	if v := ms.DeletedAt; v != nil {
		builder.WriteString(", deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", name=")
	builder.WriteString(ms.Name)
	builder.WriteByte(')')
	return builder.String()
}

// MentorshipSystems is a parsable slice of MentorshipSystem.
type MentorshipSystems []*MentorshipSystem

func (ms MentorshipSystems) config(cfg config) {
	for _i := range ms {
		ms[_i].config = cfg
	}
}
