// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Charm is the predicate function for charm builders.
type Charm func(*sql.Selector)

// CharmCreator is the predicate function for charmcreator builders.
type CharmCreator func(*sql.Selector)

// CharmModel is the predicate function for charmmodel builders.
type CharmModel func(*sql.Selector)

// Garden is the predicate function for garden builders.
type Garden func(*sql.Selector)

// Lily is the predicate function for lily builders.
type Lily func(*sql.Selector)

// LilySkill is the predicate function for lilyskill builders.
type LilySkill func(*sql.Selector)

// Mentorship is the predicate function for mentorship builders.
type Mentorship func(*sql.Selector)

// Skill is the predicate function for skill builders.
type Skill func(*sql.Selector)
